name = "estatistica"
compatibility_date = "2024-11-24"

# Diretório de assets
[build]
  upload = { format = "service-worker", directory = "./" }

[functions]
  # Defina a função para lidar com erros
  [functions.handle-error]
    path = "functions/handle-error.js"
    routes = [
      "/*",  # Rota para capturar todas as requisições e redirecionar para a função handle-error
    ]

# Configuração do assets (pasta errors)
[env]
  ASSETS = { path = "./errors" }

